version: '3'

services:

  database:
    image: postgres:latest
    container_name: inventory
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: password